import type { ImagePixelatorStyles } from '../interfaces'

export const styles: ImagePixelatorStyles = {
  container: {
    background: 'linear-gradient(135deg, var(--color-bg), #16213e)',
  },
  card: {
    maxWidth: 520,
    padding: 24,
  },
  title: {
    margin: '0 0 4px',
    fontSize: '1.5rem',
    fontWeight: 800,
    textAlign: 'center',
  },
  subtitle: {
    margin: '0 0 18px',
    fontSize: 13,
    opacity: 0.5,
    textAlign: 'center',
  },
  sourceRow: {
    display: 'flex',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 16,
  },
  sourceBtn: {
    padding: '12px 20px',
    borderRadius: 12,
    border: '1.5px solid #444',
    background: '#2a2a3a',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  cameraWrap: {
    position: 'relative',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 16,
  },
  video: {
    width: '100%',
    borderRadius: 12,
    display: 'block',
  },
  cameraBtnRow: {
    display: 'flex',
    gap: 10,
    justifyContent: 'center',
    padding: '12px 0',
  },
  captureBtn: {
    padding: '10px 24px',
    background: '#ef4444',
    border: 'none',
    borderRadius: 10,
    color: '#fff',
    fontWeight: 700,
    fontSize: 15,
    cursor: 'pointer',
  },
  cancelBtn: {
    padding: '10px 24px',
    background: '#555',
    border: 'none',
    borderRadius: 10,
    color: '#fff',
    fontWeight: 700,
    fontSize: 15,
    cursor: 'pointer',
  },
  canvasWrap: {
    borderRadius: 'var(--radius-md)',
    overflow: 'hidden',
    border: '1px solid var(--color-border-strong)',
    marginBottom: 16,
    lineHeight: 0,
  },
  canvas: {
    width: '100%',
    height: 'auto',
    display: 'block',
    imageRendering: 'pixelated',
  },
  controlGroup: {
    marginBottom: 16,
  },
  sliderLabel: {
    display: 'block',
    fontSize: 14,
    marginBottom: 6,
    opacity: 0.8,
  },
  slider: {
    width: '100%',
    cursor: 'pointer',
  },
  sliderTicks: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 11,
    opacity: 0.35,
    marginTop: 2,
  },
  actionRow: {
    display: 'flex',
    gap: 10,
    marginTop: 8,
  },
  actionBtn: {
    flex: 1,
    padding: '12px 0',
    borderRadius: 12,
    border: 'none',
    color: '#fff',
    fontWeight: 700,
    fontSize: 14,
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  info: {
    marginTop: 12,
    textAlign: 'center',
    fontSize: 13,
    opacity: 0.5,
  },
}
