import type { DCDeckBuilderStyles } from '../interfaces'

export const styles: DCDeckBuilderStyles = {
  container: {
    maxWidth: 960,
    margin: '0 auto',
    padding: '1.5rem 1rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  header: {
    textAlign: 'center',
    padding: '2rem 1.5rem 1.5rem',
  },
  title: {
    fontSize: 'clamp(1.5rem, 4vw, 2.2rem)',
    fontWeight: 800,
    margin: 0,
    background: 'linear-gradient(135deg, #3b82f6, #60a5fa, #f59e0b)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    color: '#94a3b8',
    margin: '0.5rem 0 1rem',
    fontSize: '0.95rem',
  },
  headerActions: {
    display: 'flex',
    gap: '0.5rem',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  btnSmall: {
    padding: '0.45rem 1rem',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '0.85rem',
    background: '#3b82f6',
    color: '#fff',
    transition: 'opacity 0.15s',
  },
  /* Scoreboard */
  scoreboard: {
    padding: '1.5rem',
  },
  leaderList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginTop: '0.75rem',
  },
  leaderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.75rem 1rem',
    borderRadius: 10,
    background: 'rgba(255,255,255,0.04)',
  },
  leaderRank: { fontSize: '1.3rem', minWidth: 36, textAlign: 'center' },
  leaderName: { flex: 1, fontWeight: 600, color: '#e2e8f0' },
  leaderVP: { fontWeight: 700, color: '#fbbf24', fontSize: '1.1rem' },
  leaderCards: { color: '#94a3b8', fontSize: '0.85rem' },
  /* Game log */
  logPanel: { padding: '1.5rem' },
  logScroll: {
    maxHeight: 200,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
    marginTop: '0.5rem',
  },
  logEntry: {
    display: 'flex',
    gap: '0.75rem',
    fontSize: '0.85rem',
    padding: '0.3rem 0',
    borderBottom: '1px solid rgba(255,255,255,0.04)',
  },
  logTime: { color: '#64748b', fontFamily: 'monospace', minWidth: 80 },
  logText: { color: '#cbd5e1' },
  /* Player tabs */
  playersCard: { padding: '1.25rem' },
  playerTabs: {
    display: 'flex',
    gap: '0.4rem',
    flexWrap: 'wrap',
    marginBottom: '1rem',
  },
  playerTab: {
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.85rem',
    transition: 'all 0.15s',
  },
  addPlayerBtn: {
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: '1px dashed rgba(255,255,255,0.2)',
    background: 'transparent',
    cursor: 'pointer',
    color: '#64748b',
    fontSize: '0.85rem',
  },
  playerDetail: { padding: '0.5rem 0' },
  playerInfoRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    flexWrap: 'wrap',
    marginBottom: '1rem',
  },
  nameInput: {
    flex: '1 1 180px',
    padding: '0.6rem 0.8rem',
    borderRadius: 8,
    border: '2px solid',
    background: 'rgba(255,255,255,0.06)',
    color: '#e2e8f0',
    fontSize: '1rem',
    fontWeight: 600,
    outline: 'none',
  },
  vpBadge: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    background: 'rgba(251,191,36,0.12)',
    padding: '0.5rem 1.2rem',
    borderRadius: 12,
    minWidth: 80,
  },
  vpBigNum: { fontSize: '1.8rem', fontWeight: 800, color: '#fbbf24' },
  vpLabel: { fontSize: '0.7rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: 1 },
  removeBtn: {
    padding: '0.4rem 0.8rem',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    background: 'rgba(239,68,68,0.15)',
    color: '#ef4444',
    fontSize: '0.8rem',
    fontWeight: 600,
  },
  bonusRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  bonusLabel: { color: '#94a3b8', fontSize: '0.85rem' },
  bonusInput: {
    width: 70,
    padding: '0.4rem',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.15)',
    background: 'rgba(255,255,255,0.06)',
    color: '#e2e8f0',
    fontSize: '0.95rem',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#e2e8f0',
    margin: '0.5rem 0',
  },
  muted: {
    color: '#64748b',
    fontSize: '0.9rem',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: '1rem',
  },
  /* Player deck grid */
  deckGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '0.5rem',
    marginTop: '0.5rem',
  },
  deckCard: {
    background: 'rgba(255,255,255,0.05)',
    borderRadius: 10,
    padding: '0.65rem 0.8rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.3rem',
  },
  deckCardTop: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
  },
  deckCardEmoji: { fontSize: '1.1rem' },
  deckCardName: { flex: 1, fontWeight: 600, color: '#e2e8f0', fontSize: '0.85rem' },
  qtyBadge: {
    background: '#3b82f6',
    color: '#fff',
    fontSize: '0.7rem',
    fontWeight: 700,
    borderRadius: 6,
    padding: '0.1rem 0.4rem',
  },
  deckCardBot: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    fontSize: '0.78rem',
  },
  deckCardType: { color: '#94a3b8', flex: 1 },
  deckCardVP: { fontWeight: 700, color: '#fbbf24' },
  removeMiniBtn: {
    width: 24, height: 24,
    borderRadius: 6,
    border: 'none',
    cursor: 'pointer',
    background: 'rgba(239,68,68,0.2)',
    color: '#ef4444',
    fontWeight: 700,
    fontSize: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  },
  addMiniBtn: {
    width: 24, height: 24,
    borderRadius: 6,
    border: 'none',
    cursor: 'pointer',
    background: 'rgba(59,130,246,0.2)',
    color: '#60a5fa',
    fontWeight: 700,
    fontSize: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  },
  /* VP Breakdown */
  breakdownWrap: {
    marginTop: '1rem',
    padding: '0.75rem 1rem',
    background: 'rgba(255,255,255,0.03)',
    borderRadius: 10,
  },
  breakdownTitle: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: '#94a3b8',
    margin: '0 0 0.5rem',
  },
  breakdownGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
    gap: '0.4rem',
  },
  breakdownItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0.35rem 0.5rem',
    borderRadius: 6,
    background: 'rgba(255,255,255,0.04)',
    color: '#cbd5e1',
    fontSize: '0.85rem',
  },
  /* Card Catalog */
  catalogCard: { padding: '1.25rem' },
  catalogControls: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.6rem',
    marginBottom: '0.75rem',
  },
  searchInput: {
    width: '100%',
    padding: '0.6rem 0.8rem',
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.06)',
    color: '#e2e8f0',
    fontSize: '0.95rem',
    outline: 'none',
    boxSizing: 'border-box',
  },
  filterRow: {
    display: 'flex',
    gap: '0.35rem',
    flexWrap: 'wrap',
  },
  filterBtn: {
    padding: '0.35rem 0.8rem',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.78rem',
    fontWeight: 600,
    transition: 'all 0.15s',
  },
  customToggle: {
    alignSelf: 'flex-start',
    padding: '0.4rem 0.9rem',
    borderRadius: 8,
    border: '1px dashed rgba(255,255,255,0.2)',
    background: 'transparent',
    cursor: 'pointer',
    color: '#94a3b8',
    fontSize: '0.85rem',
  },
  customForm: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap',
    marginBottom: '0.75rem',
    padding: '0.75rem',
    background: 'rgba(255,255,255,0.04)',
    borderRadius: 10,
  },
  customInput: {
    flex: '1 1 140px',
    padding: '0.5rem 0.7rem',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.06)',
    color: '#e2e8f0',
    fontSize: '0.9rem',
  },
  customSelect: {
    padding: '0.5rem',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.08)',
    color: '#e2e8f0',
    fontSize: '0.85rem',
  },
  customVpInput: {
    width: 60,
    padding: '0.5rem',
    borderRadius: 6,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(255,255,255,0.06)',
    color: '#e2e8f0',
    fontSize: '0.9rem',
    textAlign: 'center',
  },
  customSubmit: {
    padding: '0.5rem 1rem',
    borderRadius: 8,
    border: 'none',
    cursor: 'pointer',
    background: '#22c55e',
    color: '#fff',
    fontWeight: 600,
    fontSize: '0.85rem',
  },
  catalogGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
    gap: '0.5rem',
  },
  catalogItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.2rem',
    padding: '0.7rem 0.5rem',
    borderRadius: 10,
    border: '2px solid',
    background: 'rgba(255,255,255,0.04)',
    cursor: 'pointer',
    transition: 'all 0.15s',
    textAlign: 'center',
  },
  catEmoji: { fontSize: '1.4rem' },
  catName: { fontWeight: 600, color: '#e2e8f0', fontSize: '0.82rem', lineHeight: 1.2 },
  catVP: { fontWeight: 700, color: '#fbbf24', fontSize: '0.85rem' },
  catType: { color: '#64748b', fontSize: '0.72rem' },
  catOwned: {
    background: '#3b82f6',
    color: '#fff',
    fontSize: '0.65rem',
    fontWeight: 700,
    borderRadius: 6,
    padding: '0.1rem 0.4rem',
  },
}
