import type { DeckBuilderTierListStyles } from '../interfaces'

export const styles: DeckBuilderTierListStyles = {
  container: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: '2rem 1rem',
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    color: '#e2e8f0',
  },
  header: {
    textAlign: 'center',
    marginBottom: '1.5rem',
  },
  title: {
    fontSize: 'clamp(1.6rem, 4vw, 2.4rem)',
    margin: 0,
    background: 'linear-gradient(135deg, #f59e0b, #ef4444, #a855f7)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    color: '#94a3b8',
    marginTop: '0.4rem',
    fontSize: '0.95rem',
  },

  /* toolbar */
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    flexWrap: 'wrap',
    marginBottom: '1rem',
    padding: '0.6rem 1rem',
    background: 'rgba(255,255,255,0.04)',
    borderRadius: 10,
  },
  searchInput: {
    flex: '1 1 180px',
    padding: '0.45rem 0.75rem',
    borderRadius: 8,
    border: '1px solid #334155',
    background: '#1e293b',
    color: '#e2e8f0',
    fontSize: '0.9rem',
    outline: 'none',
  },
  stats: {
    color: '#64748b',
    fontSize: '0.85rem',
    whiteSpace: 'nowrap',
  },
  confirmGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
  },
  confirmText: {
    color: '#fbbf24',
    fontSize: '0.85rem',
  },
  btn: {
    padding: '0.35rem 0.75rem',
    borderRadius: 6,
    border: '1px solid #475569',
    background: '#334155',
    color: '#e2e8f0',
    cursor: 'pointer',
    fontSize: '0.85rem',
    whiteSpace: 'nowrap',
  },
  btnDanger: {
    background: '#dc2626',
    borderColor: '#dc2626',
    color: '#fff',
  },

  /* tier list */
  tierList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    borderRadius: 12,
    overflow: 'hidden',
    border: '1px solid #334155',
  },
  tierRow: {
    display: 'flex',
    minHeight: 72,
    transition: 'background 0.15s',
    background: 'rgba(30,41,59,0.6)',
  },
  tierRowHover: {
    background: 'rgba(100,116,139,0.25)',
    boxShadow: 'inset 0 0 0 2px #64748b',
  },
  tierLabel: {
    width: 100,
    minWidth: 100,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.5rem 0.25rem',
    color: '#1a1a2e',
    userSelect: 'none',
  },
  tierLetter: {
    fontSize: '1.8rem',
    fontWeight: 900,
    lineHeight: 1,
  },
  tierDesc: {
    fontSize: '0.55rem',
    textAlign: 'center',
    fontWeight: 600,
    opacity: 0.8,
    marginTop: 2,
    lineHeight: 1.2,
    padding: '0 4px',
  },
  tierGames: {
    flex: 1,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    padding: '8px 10px',
    minHeight: 56,
  },
  emptySlot: {
    color: '#475569',
    fontSize: '0.8rem',
    fontStyle: 'italic',
  },

  /* game cards */
  gameCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 5,
    padding: '6px 10px',
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 8,
    cursor: 'grab',
    userSelect: 'none',
    transition: 'transform 0.12s, box-shadow 0.12s',
    fontSize: '0.82rem',
    position: 'relative',
  },
  gameCardDragging: {
    opacity: 0.4,
    transform: 'scale(0.95)',
  },
  gameCardMoved: {
    borderColor: '#7c3aed',
    boxShadow: '0 0 6px rgba(124,58,237,0.3)',
  },
  gameEmoji: {
    fontSize: '1.1rem',
  },
  gameName: {
    fontWeight: 600,
    color: '#e2e8f0',
    whiteSpace: 'nowrap',
  },
  movedBadge: {
    color: '#a78bfa',
    fontWeight: 700,
    fontSize: '0.75rem',
    marginLeft: 2,
  },

  /* detail panel */
  detailOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '1rem',
  },
  detailPanel: {
    background: '#1e293b',
    borderRadius: 16,
    padding: '2rem',
    maxWidth: 420,
    width: '100%',
    position: 'relative',
    border: '1px solid #334155',
    boxShadow: '0 24px 48px rgba(0,0,0,0.4)',
  },
  detailClose: {
    position: 'absolute',
    top: 12,
    right: 14,
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    fontSize: '1.2rem',
    cursor: 'pointer',
  },
  detailEmoji: {
    fontSize: '3rem',
    textAlign: 'center',
  },
  detailTitle: {
    textAlign: 'center',
    margin: '0.5rem 0 0.75rem',
    fontSize: '1.4rem',
    color: '#f8fafc',
  },
  detailMeta: {
    display: 'flex',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    marginBottom: '1rem',
  },
  metaTag: {
    padding: '3px 10px',
    borderRadius: 20,
    background: 'rgba(255,255,255,0.08)',
    fontSize: '0.8rem',
    color: '#94a3b8',
    whiteSpace: 'nowrap',
  },
  detailDesc: {
    color: '#cbd5e1',
    fontSize: '0.95rem',
    textAlign: 'center',
    lineHeight: 1.5,
    marginBottom: '1.25rem',
  },
  moveBtns: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  moveLabel: {
    color: '#64748b',
    fontSize: '0.8rem',
    marginRight: 4,
  },
  moveBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    border: 'none',
    fontWeight: 800,
    fontSize: '0.95rem',
    cursor: 'pointer',
    transition: 'transform 0.1s',
  },

  /* legend */
  legend: {
    marginTop: '1.5rem',
    padding: '1rem 1.25rem',
    background: 'rgba(255,255,255,0.03)',
    borderRadius: 10,
    border: '1px solid #1e293b',
  },
  legendTitle: {
    margin: '0 0 0.5rem',
    fontWeight: 700,
    color: '#94a3b8',
    fontSize: '0.85rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  legendList: {
    margin: 0,
    paddingLeft: '1.2rem',
    color: '#64748b',
    fontSize: '0.85rem',
    lineHeight: 1.7,
  },
}
