import type { AngerStage } from '../interfaces'

export const ANGER_STAGES: AngerStage[] = [
  {
    level: 0,
    face: '🟢',
    label: 'Calm Shrek',
    quote: "What are ye doin' in my swamp?",
    bgColor: '#2d5a27',
    shakeIntensity: 0,
    faceSize: 120,
    textColor: '#a8e6a3',
  },
  {
    level: 1,
    face: '🟢',
    label: 'Mildly Annoyed',
    quote: "For your information, there's a LOT more to ogres than people think.",
    bgColor: '#3a6b2a',
    shakeIntensity: 1,
    faceSize: 130,
    textColor: '#c4f0b8',
  },
  {
    level: 2,
    face: '🟢',
    label: 'Irritated',
    quote: "DONKEY! I told ye, ogres are like onions!",
    bgColor: '#4a7828',
    shakeIntensity: 2,
    faceSize: 145,
    textColor: '#d4f5c0',
  },
  {
    level: 3,
    face: '🟢',
    label: 'Bothered',
    quote: "Oh, ye think this is funny, do ye?",
    bgColor: '#5a8020',
    shakeIntensity: 3,
    faceSize: 160,
    textColor: '#e0f0a0',
  },
  {
    level: 4,
    face: '🟢',
    label: 'Agitated',
    quote: "I'm an OGRE! Doesn't that bother you?!",
    bgColor: '#6a8818',
    shakeIntensity: 5,
    faceSize: 175,
    textColor: '#f0e880',
  },
  {
    level: 5,
    face: '🟢',
    label: 'Angry',
    quote: "STOP POKING ME! I'm warning ye!",
    bgColor: '#807010',
    shakeIntensity: 8,
    faceSize: 190,
    textColor: '#ffe060',
  },
  {
    level: 6,
    face: '🟢',
    label: 'Furious',
    quote: "That'll do, DONKEY! THAT'LL DO!!",
    bgColor: '#905808',
    shakeIntensity: 12,
    faceSize: 210,
    textColor: '#ffc040',
  },
  {
    level: 7,
    face: '🟢',
    label: 'Enraged',
    quote: "WHAT DID I SAY ABOUT MY SWAMP?!?!",
    bgColor: '#a04000',
    shakeIntensity: 16,
    faceSize: 230,
    textColor: '#ff9020',
  },
  {
    level: 8,
    face: '🟢',
    label: 'Livid',
    quote: "GET OUT OF MY SWAMP!! GET OOOOUT!!!",
    bgColor: '#b02800',
    shakeIntensity: 22,
    faceSize: 250,
    textColor: '#ff6030',
  },
  {
    level: 9,
    face: '🟢',
    label: 'NUCLEAR',
    quote: "RRRROOOAAARRR!!! THIS IS MY SWAAAAAAMP!!!",
    bgColor: '#c01000',
    shakeIntensity: 30,
    faceSize: 280,
    textColor: '#ff2020',
  },
  {
    level: 10,
    face: '🟢',
    label: '☠️ BEYOND RAGE ☠️',
    quote: "...... *heavy breathing* ..... ye've done it now, laddie.....",
    bgColor: '#1a0000',
    shakeIntensity: 0,
    faceSize: 320,
    textColor: '#ff0000',
  },
]

export const CLICK_SPLASHES = [
  'OOF!',
  'HEY!',
  'STOP!',
  'OI!',
  'QUIT IT!',
  'GRRRR!',
  'ROAR!',
  'ME SWAMP!',
  'LAYERS!!',
  'DONKEY!!',
  'NO!!',
  'AARGH!',
  '*STOMP*',
  'ENOUGH!',
]

export const SWAMP_PARTICLES = ['🧅', '🧄', '🕯️', '🪵', '🐸', '🦟', '🌿', '💚']
