import type { Location } from '../interfaces'

export const LOCATIONS: Location[] = [
  {
    id: 1,
    name: 'Eiffel Tower',
    coordinates: { lat: 48.8584, lng: 2.2945 },
    clue: 'An iron lattice tower built for a world fair in 1889, named after its engineer.',
    emoji: '🗼',
    region: 'Europe',
  },
  {
    id: 2,
    name: 'Great Wall of China',
    coordinates: { lat: 40.4319, lng: 116.5704 },
    clue: 'An ancient series of fortifications stretching over 13,000 miles, visible from space (myth!).',
    emoji: '🏯',
    region: 'Asia',
  },
  {
    id: 3,
    name: 'Machu Picchu',
    coordinates: { lat: -13.1631, lng: -72.545 },
    clue: 'A 15th-century Incan citadel perched high in the Andes mountains.',
    emoji: '🏔️',
    region: 'South America',
  },
  {
    id: 4,
    name: 'Statue of Liberty',
    coordinates: { lat: 40.6892, lng: -74.0445 },
    clue: 'A colossal copper statue gifted by France, standing on an island in a famous harbor.',
    emoji: '🗽',
    region: 'North America',
  },
  {
    id: 5,
    name: 'Sydney Opera House',
    coordinates: { lat: -33.8568, lng: 151.2153 },
    clue: 'A multi-venue performing arts centre with iconic sail-shaped roof shells.',
    emoji: '🎭',
    region: 'Oceania',
  },
  {
    id: 6,
    name: 'Colosseum',
    coordinates: { lat: 41.8902, lng: 12.4922 },
    clue: 'An ancient oval amphitheatre that once hosted gladiatorial contests.',
    emoji: '🏟️',
    region: 'Europe',
  },
  {
    id: 7,
    name: 'Christ the Redeemer',
    coordinates: { lat: -22.9519, lng: -43.2105 },
    clue: 'A 30-meter Art Deco statue atop a mountain overlooking a famous carnival city.',
    emoji: '✝️',
    region: 'South America',
  },
  {
    id: 8,
    name: 'Taj Mahal',
    coordinates: { lat: 27.1751, lng: 78.0421 },
    clue: 'An ivory-white marble mausoleum built by a Mughal emperor for his beloved wife.',
    emoji: '🕌',
    region: 'Asia',
  },
  {
    id: 9,
    name: 'Pyramids of Giza',
    coordinates: { lat: 29.9792, lng: 31.1342 },
    clue: 'Ancient monumental tombs on the outskirts of a massive city near a great river.',
    emoji: '🔺',
    region: 'Africa',
  },
  {
    id: 10,
    name: 'Stonehenge',
    coordinates: { lat: 51.1789, lng: -1.8262 },
    clue: 'A mysterious prehistoric ring of standing stones on a grassy plain.',
    emoji: '🪨',
    region: 'Europe',
  },
  {
    id: 11,
    name: 'Mount Fuji',
    coordinates: { lat: 35.3606, lng: 138.7274 },
    clue: 'A nearly symmetrical volcanic cone, the highest peak in an island nation.',
    emoji: '🗻',
    region: 'Asia',
  },
  {
    id: 12,
    name: 'Petra',
    coordinates: { lat: 30.3285, lng: 35.4444 },
    clue: 'A "rose-red city half as old as time" — temples carved directly into sandstone cliffs.',
    emoji: '🏛️',
    region: 'Middle East',
  },
  {
    id: 13,
    name: 'Niagara Falls',
    coordinates: { lat: 43.0962, lng: -79.0377 },
    clue: 'Massive waterfalls on the border between two countries, surrounded by casinos and tour boats.',
    emoji: '🌊',
    region: 'North America',
  },
  {
    id: 14,
    name: 'Table Mountain',
    coordinates: { lat: -33.9625, lng: 18.4039 },
    clue: 'A flat-topped mountain overlooking a city at the southern tip of a continent.',
    emoji: '⛰️',
    region: 'Africa',
  },
  {
    id: 15,
    name: 'Angkor Wat',
    coordinates: { lat: 13.4125, lng: 103.867 },
    clue: 'The largest religious structure in the world, originally a Hindu temple complex in Southeast Asia.',
    emoji: '🛕',
    region: 'Asia',
  },
  {
    id: 16,
    name: 'Big Ben',
    coordinates: { lat: 51.5007, lng: -0.1246 },
    clue: 'A famous clock tower standing beside a historic parliament building along a great river.',
    emoji: '🕰️',
    region: 'Europe',
  },
  {
    id: 17,
    name: 'Golden Gate Bridge',
    coordinates: { lat: 37.8199, lng: -122.4783 },
    clue: 'An iconic suspension bridge painted "International Orange" spanning a foggy strait.',
    emoji: '🌉',
    region: 'North America',
  },
  {
    id: 18,
    name: 'Santorini',
    coordinates: { lat: 36.3932, lng: 25.4615 },
    clue: 'A crescent-shaped volcanic island famous for white-washed buildings with blue domes.',
    emoji: '🏝️',
    region: 'Europe',
  },
  {
    id: 19,
    name: 'Chichen Itza',
    coordinates: { lat: 20.6843, lng: -88.5678 },
    clue: 'A step pyramid built by the Maya, where shadows create a serpent at the equinox.',
    emoji: '🐍',
    region: 'North America',
  },
  {
    id: 20,
    name: 'Aurora Borealis Viewing (Tromsø)',
    coordinates: { lat: 69.6496, lng: 18.9560 },
    clue: 'A city above the Arctic Circle and one of the best places to see the Northern Lights.',
    emoji: '🌌',
    region: 'Europe',
  },
]

export const ROUNDS_PER_GAME = 5

export const MAX_SCORE_PER_ROUND = 5000

/** Distance in km where score drops to zero */
export const MAX_DISTANCE_KM = 20000
