import type { BalloonPopStyles } from '../interfaces'

export const styles = {
  container: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: '100vh',
    overflow: 'hidden',
    background: '#0f0c29',
    touchAction: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    cursor: 'pointer',
  },
  canvas: {
    display: 'block',
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  overlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(15, 12, 41, 0.85)',
    backdropFilter: 'blur(8px)',
    zIndex: 10,
    cursor: 'pointer',
  },
  startCard: {
    textAlign: 'center',
    padding: '2.5rem 3rem',
    borderRadius: '24px',
    background: 'rgba(255,255,255,0.08)',
    border: '1px solid rgba(255,255,255,0.15)',
    maxWidth: '400px',
  },
  startEmoji: {
    fontSize: '3.5rem',
    marginBottom: '0.5rem',
    lineHeight: 1.2,
  },
  title: {
    color: '#fff',
    fontSize: '2.4rem',
    fontWeight: 800,
    margin: '0.25rem 0',
    background: 'linear-gradient(135deg, #FF6B6B, #FECA57, #48DBFB, #FF9FF3)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  subtitle: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: '1.1rem',
    lineHeight: 1.5,
    margin: '0.75rem 0 1.5rem',
  },
  startButton: {
    background: 'linear-gradient(135deg, #FF6B6B, #FF9FF3)',
    color: '#fff',
    border: 'none',
    borderRadius: '16px',
    padding: '1rem 2.5rem',
    fontSize: '1.3rem',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 4px 24px rgba(255,107,107,0.4)',
    transition: 'transform 0.15s',
    pointerEvents: 'none',
  },
  hint: {
    color: 'rgba(255,255,255,0.45)',
    fontSize: '0.85rem',
    marginTop: '1rem',
  },
} satisfies BalloonPopStyles
