import { SIZE } from './themeConfig'
import type { ColorSudokuStyles } from '../interfaces'

export const styles: ColorSudokuStyles = {
  container: {
    background: 'linear-gradient(135deg, #0f0c29, #302b63, #24243e)',
  },
  title: {
    margin: 0,
    fontSize: 'clamp(1.4rem, 4vw, 2rem)',
    fontWeight: 800,
    letterSpacing: 1,
  },
  subtitle: {
    margin: '4px 0 10px',
    fontSize: 'clamp(0.75rem, 2vw, 0.9rem)',
    opacity: 0.7,
  },
  winBanner: {
    padding: '10px 24px',
    background: 'rgba(34,197,94,0.25)',
    border: '1px solid #22c55e',
    borderRadius: 12,
    fontSize: '1.1rem',
    fontWeight: 700,
    marginBottom: 10,
  },
  themeRow: {
    position: 'relative',
    marginBottom: 8,
    zIndex: 20,
  },
  themeToggle: {
    padding: '8px 20px',
    background: 'rgba(99,102,241,0.25)',
    border: '1px solid rgba(129,140,248,0.4)',
    borderRadius: 10,
    color: '#fff',
    fontWeight: 700,
    fontSize: '0.95rem',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  themeMenu: {
    position: 'absolute',
    top: '110%',
    left: '50%',
    transform: 'translateX(-50%)',
    background: 'rgba(20,18,50,0.97)',
    border: '1px solid rgba(129,140,248,0.3)',
    borderRadius: 14,
    padding: 8,
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 6,
    minWidth: 320,
    maxWidth: '92vw',
    backdropFilter: 'blur(12px)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.6)',
  },
  themeOption: {
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid',
    color: '#fff',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'background 0.15s',
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  themeOptionLabel: {
    fontWeight: 700,
    fontSize: '0.9rem',
  },
  themeOptionDesc: {
    fontSize: '0.72rem',
    opacity: 0.6,
  },
  diffRow: {
    display: 'flex',
    gap: 8,
    marginBottom: 12,
  },
  diffBtn: {
    padding: '6px 18px',
    border: '1px solid',
    borderRadius: 8,
    color: '#fff',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 13,
    transition: 'background 0.15s',
  },
  board: {
    display: 'grid',
    gridTemplateColumns: `repeat(${SIZE}, 1fr)`,
    width: 'min(90vw, 440px)',
    aspectRatio: '1',
    borderRadius: 10,
    overflow: 'hidden',
    border: '2.5px solid rgba(255,255,255,0.6)',
    boxShadow: '0 4px 30px rgba(0,0,0,0.4)',
  },
  cell: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 0.18s, opacity 0.15s, transform 0.1s',
    position: 'relative',
    lineHeight: 1,
    touchAction: 'manipulation',
  },
  palette: {
    display: 'flex',
    gap: 8,
    marginTop: 14,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  paletteBtn: {
    width: 38,
    height: 38,
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    transition: 'transform 0.15s, outline 0.15s, box-shadow 0.15s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
    touchAction: 'manipulation',
  },
  eraseBtn: {
    width: 38,
    height: 38,
    borderRadius: '50%',
    border: '2px solid rgba(255,255,255,0.3)',
    background: 'rgba(60,60,60,0.8)',
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'transform 0.15s',
    touchAction: 'manipulation',
  },
  legend: {
    display: 'flex',
    gap: 10,
    marginTop: 12,
    flexWrap: 'wrap',
    justifyContent: 'center',
    opacity: 0.65,
    fontSize: '0.75rem',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 3,
  },
  legendSwatch: {
    width: 12,
    height: 12,
    borderRadius: 3,
    display: 'inline-block',
    transition: 'background 0.3s',
  },
} satisfies ColorSudokuStyles
