import type { VideoToGifStyles } from '../interfaces'

export const styles: VideoToGifStyles = {
  container: {
    maxWidth: 700,
    margin: '0 auto',
    padding: '2rem 1rem',
    fontFamily: "'Segoe UI', system-ui, -apple-system, sans-serif",
    color: '#f0f4ff',
  },
  title: {
    fontSize: '2rem',
    marginBottom: '0.25rem',
    textAlign: 'center',
  },
  subtitle: {
    textAlign: 'center',
    color: '#94a3b8',
    marginBottom: '2rem',
    lineHeight: 1.5,
  },
  uploadArea: {
    textAlign: 'center',
    marginBottom: '1.5rem',
  },
  fileInput: {
    display: 'none',
  },
  uploadLabel: {
    display: 'inline-block',
    padding: '0.75rem 2rem',
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff',
    borderRadius: 12,
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 600,
    transition: 'transform 0.15s, box-shadow 0.15s',
    boxShadow: '0 4px 14px rgba(99, 102, 241, 0.4)',
  },
  videoPreview: {
    width: '100%',
    maxHeight: 360,
    borderRadius: 12,
    marginBottom: '1.5rem',
    background: '#000',
  },
  settings: {
    background: 'rgba(255,255,255,0.06)',
    borderRadius: 16,
    padding: '1.5rem',
    marginBottom: '1.5rem',
  },
  settingsTitle: {
    margin: '0 0 1rem',
    fontSize: '1.1rem',
  },
  settingsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
    gap: '1rem',
    marginBottom: '1.25rem',
  },
  label: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    fontSize: '0.85rem',
    color: '#cbd5e1',
  },
  input: {
    padding: '0.5rem',
    borderRadius: 8,
    border: '1px solid rgba(255,255,255,0.15)',
    background: 'rgba(0,0,0,0.3)',
    color: '#f0f4ff',
    fontSize: '1rem',
    width: '100%',
    boxSizing: 'border-box',
  },
  convertBtn: {
    display: 'block',
    width: '100%',
    padding: '0.85rem',
    border: 'none',
    borderRadius: 12,
    background: 'linear-gradient(135deg, #10b981, #059669)',
    color: '#fff',
    fontSize: '1.05rem',
    fontWeight: 700,
    cursor: 'pointer',
    boxShadow: '0 4px 14px rgba(16, 185, 129, 0.35)',
  },
  progressBarOuter: {
    marginTop: '0.75rem',
    height: 8,
    borderRadius: 4,
    background: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  progressBarInner: {
    height: '100%',
    borderRadius: 4,
    background: 'linear-gradient(90deg, #10b981, #34d399)',
    transition: 'width 0.3s ease',
  },
  error: {
    color: '#f87171',
    textAlign: 'center',
    marginBottom: '1rem',
  },
  result: {
    textAlign: 'center',
    background: 'rgba(255,255,255,0.06)',
    borderRadius: 16,
    padding: '1.5rem',
  },
  resultTitle: {
    marginTop: 0,
    marginBottom: '1rem',
  },
  gifPreview: {
    maxWidth: '100%',
    borderRadius: 12,
    marginBottom: '1rem',
    boxShadow: '0 4px 24px rgba(0,0,0,0.4)',
  },
  resultActions: {
    display: 'flex',
    gap: '1rem',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  downloadBtn: {
    padding: '0.7rem 1.5rem',
    border: 'none',
    borderRadius: 10,
    background: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    color: '#fff',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  resetBtn: {
    padding: '0.7rem 1.5rem',
    border: '1px solid rgba(255,255,255,0.2)',
    borderRadius: 10,
    background: 'transparent',
    color: '#cbd5e1',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
}
