import type { WaifuCharacter } from '../interfaces'

/**
 * Curated roster of popular anime / manga / game characters used by the
 * Waifu Generator. Each entry is tagged with the filterable traits so the
 * page can narrow results based on user selections.
 */
export const WAIFU_ROSTER: WaifuCharacter[] = [
  // ── Girls ──────────────────────────────────────────────────────────
  {
    name: 'Rem',
    series: 'Re:Zero',
    gender: 'girl',
    hairColor: 'blue',
    eyeColor: 'blue',
    personality: 'dandere',
    sourceMedia: 'light-novel',
    emoji: '💙',
    quote: 'I love you… from the very beginning.',
    traits: ['Loyal', 'Hard-working', 'Twin maid'],
    imageUrl: '/images/waifu/rem.jpg',
  },
  {
    name: 'Zero Two',
    series: 'Darling in the Franxx',
    gender: 'girl',
    hairColor: 'pink',
    eyeColor: 'green',
    personality: 'genki',
    sourceMedia: 'anime',
    emoji: '🌸',
    quote: 'I found you, my darling.',
    traits: ['Bold', 'Mysterious', 'Klaxosaur hybrid'],
    imageUrl: '/images/waifu/zero-two.jpg',
  },
  {
    name: 'Asuka Langley',
    series: 'Neon Genesis Evangelion',
    gender: 'girl',
    hairColor: 'red',
    eyeColor: 'blue',
    personality: 'tsundere',
    sourceMedia: 'anime',
    emoji: '🔥',
    quote: "Are you stupid?! Don't just stand there!",
    traits: ['Proud', 'Competitive', 'Eva pilot'],
    imageUrl: '/images/waifu/asuka-langley.jpg',
  },
  {
    name: 'Hinata Hyuga',
    series: 'Naruto',
    gender: 'girl',
    hairColor: 'blue',
    eyeColor: 'purple',
    personality: 'dandere',
    sourceMedia: 'manga',
    emoji: '🌙',
    quote: 'I will never go back on my word…',
    traits: ['Shy', 'Determined', 'Byakugan user'],
    imageUrl: '/images/waifu/hinata-hyuga.jpg',
  },
  {
    name: 'Mikasa Ackerman',
    series: 'Attack on Titan',
    gender: 'girl',
    hairColor: 'black',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '⚔️',
    quote: 'If I cannot, then I will die. But if I win, I live.',
    traits: ['Fierce', 'Protective', 'Ackerman bloodline'],
    imageUrl: '/images/waifu/mikasa-ackerman.jpg',
  },
  {
    name: 'Tohru',
    series: "Miss Kobayashi's Dragon Maid",
    gender: 'girl',
    hairColor: 'blonde',
    eyeColor: 'red',
    personality: 'genki',
    sourceMedia: 'manga',
    emoji: '🐉',
    quote: 'I want to be with Kobayashi forever!',
    traits: ['Cheerful', 'Dragon form', 'Devoted'],
    imageUrl: '/images/waifu/tohru.jpg',
  },
  {
    name: 'Yor Forger',
    series: 'Spy × Family',
    gender: 'girl',
    hairColor: 'black',
    eyeColor: 'red',
    personality: 'dandere',
    sourceMedia: 'manga',
    emoji: '🗡️',
    quote: 'I will protect my family.',
    traits: ['Assassin', 'Caring mother', 'Strong'],
    imageUrl: '/images/waifu/yor-forger.jpg',
  },
  {
    name: 'Marin Kitagawa',
    series: 'My Dress-Up Darling',
    gender: 'girl',
    hairColor: 'blonde',
    eyeColor: 'brown',
    personality: 'genki',
    sourceMedia: 'manga',
    emoji: '✨',
    quote: "I just wanna cosplay the characters I love!",
    traits: ['Outgoing', 'Cosplayer', 'Supportive'],
    imageUrl: '/images/waifu/marin-kitagawa.jpg',
  },
  {
    name: 'Makima',
    series: 'Chainsaw Man',
    gender: 'girl',
    hairColor: 'red',
    eyeColor: 'amber',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '🐾',
    quote: 'I want a family.',
    traits: ['Manipulative', 'Powerful', 'Control Devil'],
    imageUrl: '/images/waifu/makima.jpg',
  },
  {
    name: 'Nezuko Kamado',
    series: 'Demon Slayer',
    gender: 'girl',
    hairColor: 'black',
    eyeColor: 'pink',
    personality: 'dandere',
    sourceMedia: 'manga',
    emoji: '🎋',
    quote: '…(muffled determination)',
    traits: ['Demon', 'Protective sister', 'Resilient'],
    imageUrl: '/images/waifu/nezuko-kamado.jpg',
  },
  {
    name: 'Sakura Haruno',
    series: 'Naruto',
    gender: 'girl',
    hairColor: 'pink',
    eyeColor: 'green',
    personality: 'tsundere',
    sourceMedia: 'manga',
    emoji: '🌸',
    quote: "I'm not going to be a burden anymore!",
    traits: ['Medical ninja', 'Strong punch', 'Determined'],
    imageUrl: '/images/waifu/sakura-haruno.jpg',
  },
  {
    name: 'Erza Scarlet',
    series: 'Fairy Tail',
    gender: 'girl',
    hairColor: 'red',
    eyeColor: 'brown',
    personality: 'ojou-sama',
    sourceMedia: 'manga',
    emoji: '⚔️',
    quote: 'All I need is the power to protect my comrades.',
    traits: ['Armor mage', 'Strict', 'Cake lover'],
    imageUrl: '/images/waifu/erza-scarlet.jpg',
  },
  {
    name: 'C.C.',
    series: 'Code Geass',
    gender: 'girl',
    hairColor: 'green',
    eyeColor: 'amber',
    personality: 'kuudere',
    sourceMedia: 'anime',
    emoji: '🍕',
    quote: 'I am not alone. Because you are here.',
    traits: ['Immortal', 'Aloof', 'Pizza fiend'],
    imageUrl: '/images/waifu/cc.jpg',
  },
  {
    name: 'Nami',
    series: 'One Piece',
    gender: 'girl',
    hairColor: 'orange',
    eyeColor: 'brown',
    personality: 'tsundere',
    sourceMedia: 'manga',
    emoji: '🗺️',
    quote: 'Luffy… help me.',
    traits: ['Navigator', 'Money-loving', 'Resourceful'],
    imageUrl: '/images/waifu/nami.jpg',
  },
  {
    name: 'Nico Robin',
    series: 'One Piece',
    gender: 'girl',
    hairColor: 'black',
    eyeColor: 'blue',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '📚',
    quote: 'I want to live!',
    traits: ['Archaeologist', 'Calm', 'Hana Hana no Mi'],
    imageUrl: '/images/waifu/nico-robin.jpg',
  },
  {
    name: 'Violet Evergarden',
    series: 'Violet Evergarden',
    gender: 'girl',
    hairColor: 'blonde',
    eyeColor: 'blue',
    personality: 'kuudere',
    sourceMedia: 'light-novel',
    emoji: '✉️',
    quote: 'I want to know what "I love you" means.',
    traits: ['Auto Memory Doll', 'Former soldier', 'Eloquent'],
    imageUrl: '/images/waifu/violet-evergarden.jpg',
  },
  {
    name: 'Raphtalia',
    series: 'The Rising of the Shield Hero',
    gender: 'girl',
    hairColor: 'brown',
    eyeColor: 'red',
    personality: 'dandere',
    sourceMedia: 'light-novel',
    emoji: '🦝',
    quote: 'I will always follow you, Shield Hero.',
    traits: ['Tanuki demi-human', 'Swordswoman', 'Devoted'],
    imageUrl: '/images/waifu/raphtalia.jpg',
  },
  {
    name: 'Ochaco Uraraka',
    series: 'My Hero Academia',
    gender: 'girl',
    hairColor: 'brown',
    eyeColor: 'brown',
    personality: 'genki',
    sourceMedia: 'manga',
    emoji: '🌟',
    quote: "I'll become a hero for my parents' sake!",
    traits: ['Zero Gravity', 'Cheerful', 'Hard-working'],
    imageUrl: '/images/waifu/ochaco-uraraka.jpg',
  },
  {
    name: 'Megumin',
    series: 'KonoSuba',
    gender: 'girl',
    hairColor: 'brown',
    eyeColor: 'red',
    personality: 'genki',
    sourceMedia: 'light-novel',
    emoji: '💥',
    quote: 'EXPLOSION!',
    traits: ['Arch Wizard', 'Chuunibyou', 'One-trick pony'],
    imageUrl: '/images/waifu/megumin.jpg',
  },
  {
    name: 'Saber (Artoria)',
    series: 'Fate/stay night',
    gender: 'girl',
    hairColor: 'blonde',
    eyeColor: 'green',
    personality: 'ojou-sama',
    sourceMedia: 'game',
    emoji: '👑',
    quote: 'I ask of you: are you my master?',
    traits: ['King Arthur', 'Noble', 'Excalibur wielder'],
    imageUrl: '/images/waifu/saber.jpg',
  },
  {
    name: '2B',
    series: 'NieR: Automata',
    gender: 'girl',
    hairColor: 'white',
    eyeColor: 'blue',
    personality: 'kuudere',
    sourceMedia: 'game',
    emoji: '⚙️',
    quote: 'Emotions are prohibited.',
    traits: ['Android', 'Combat model', 'Stoic'],
    imageUrl: '/images/waifu/2b.jpg',
  },
  {
    name: 'Tifa Lockhart',
    series: 'Final Fantasy VII',
    gender: 'girl',
    hairColor: 'brown',
    eyeColor: 'red',
    personality: 'genki',
    sourceMedia: 'game',
    emoji: '🥊',
    quote: "Words aren't the only way to tell someone how you feel.",
    traits: ['Martial artist', 'Bar owner', 'Supportive'],
    imageUrl: '/images/waifu/tifa-lockhart.jpg',
  },
  {
    name: 'Yoruichi Shihoin',
    series: 'Bleach',
    gender: 'girl',
    hairColor: 'purple',
    eyeColor: 'amber',
    personality: 'tomboy',
    sourceMedia: 'manga',
    emoji: '🐱',
    quote: 'Did I surprise you?',
    traits: ['Flash Goddess', 'Cat form', 'Playful'],
    imageUrl: '/images/waifu/yoruichi-shihoin.jpg',
  },
  {
    name: 'Bulma',
    series: 'Dragon Ball',
    gender: 'girl',
    hairColor: 'blue',
    eyeColor: 'blue',
    personality: 'tsundere',
    sourceMedia: 'manga',
    emoji: '🔧',
    quote: "I'm a genius, of course I can figure it out!",
    traits: ['Inventor', 'Sassy', 'Capsule Corp heiress'],
    imageUrl: '/images/waifu/bulma.jpg',
  },
  {
    name: 'Android 18',
    series: 'Dragon Ball Z',
    gender: 'girl',
    hairColor: 'blonde',
    eyeColor: 'blue',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '⚡',
    quote: "Don't get in my way.",
    traits: ['Android', 'Deadpan', 'Powerful'],
    imageUrl: '/images/waifu/android-18.jpg',
  },
  // ── Boys ───────────────────────────────────────────────────────────
  {
    name: 'Levi Ackerman',
    series: 'Attack on Titan',
    gender: 'boy',
    hairColor: 'black',
    eyeColor: 'blue',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '🧹',
    quote: "Give up on your dreams and die… or fight. It's your call.",
    traits: ['Clean freak', 'Strongest soldier', 'Short king'],
    imageUrl: '/images/waifu/levi-ackerman.jpg',
  },
  {
    name: 'Gojo Satoru',
    series: 'Jujutsu Kaisen',
    gender: 'boy',
    hairColor: 'white',
    eyeColor: 'blue',
    personality: 'genki',
    sourceMedia: 'manga',
    emoji: '👁️',
    quote: "Throughout heaven and earth, I alone am the honored one.",
    traits: ['Infinity', 'Blindfold', 'Six Eyes'],
    imageUrl: '/images/waifu/gojo-satoru.jpg',
  },
  {
    name: 'Tanjiro Kamado',
    series: 'Demon Slayer',
    gender: 'boy',
    hairColor: 'red',
    eyeColor: 'red',
    personality: 'genki',
    sourceMedia: 'manga',
    emoji: '🔥',
    quote: 'I will never give up!',
    traits: ['Kind', 'Water & Sun breather', 'Hanafuda earrings'],
    imageUrl: '/images/waifu/tanjiro-kamado.jpg',
  },
  {
    name: 'Spike Spiegel',
    series: 'Cowboy Bebop',
    gender: 'boy',
    hairColor: 'green',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'anime',
    emoji: '🚀',
    quote: "I'm not going there to die. I'm going to find out if I'm really alive.",
    traits: ['Bounty hunter', 'Jeet Kune Do', 'Laid-back'],
    imageUrl: '/images/waifu/spike-spiegel.jpg',
  },
  {
    name: 'Roronoa Zoro',
    series: 'One Piece',
    gender: 'boy',
    hairColor: 'green',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '🗡️',
    quote: 'Nothing happened.',
    traits: ['Three-sword style', 'Gets lost', 'Loyal'],
    imageUrl: '/images/waifu/roronoa-zoro.jpg',
  },
  {
    name: 'Todoroki Shoto',
    series: 'My Hero Academia',
    gender: 'boy',
    hairColor: 'white',
    eyeColor: 'heterochromia',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '❄️',
    quote: "I'll become a hero my own way.",
    traits: ['Half-cold Half-hot', 'Burn scar', 'Reserved'],
    imageUrl: '/images/waifu/todoroki-shoto.jpg',
  },
  {
    name: 'Kakashi Hatake',
    series: 'Naruto',
    gender: 'boy',
    hairColor: 'white',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '📖',
    quote: 'In the ninja world, those who break the rules are trash…',
    traits: ['Copy ninja', 'Always late', 'Sharingan'],
    imageUrl: '/images/waifu/kakashi-hatake.jpg',
  },
  {
    name: 'Itachi Uchiha',
    series: 'Naruto',
    gender: 'boy',
    hairColor: 'black',
    eyeColor: 'red',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '🌀',
    quote: "You don't become Hokage to be acknowledged. Those acknowledged become Hokage.",
    traits: ['Sharingan master', 'Self-sacrificing', 'Prodigy'],
    imageUrl: '/images/waifu/itachi-uchiha.jpg',
  },
  {
    name: 'Vegeta',
    series: 'Dragon Ball Z',
    gender: 'boy',
    hairColor: 'black',
    eyeColor: 'brown',
    personality: 'tsundere',
    sourceMedia: 'manga',
    emoji: '👑',
    quote: 'I am the prince of all Saiyans!',
    traits: ['Saiyan prince', 'Pride', 'Rival'],
    imageUrl: '/images/waifu/vegeta.jpg',
  },
  {
    name: 'Killua Zoldyck',
    series: 'Hunter × Hunter',
    gender: 'boy',
    hairColor: 'white',
    eyeColor: 'blue',
    personality: 'dandere',
    sourceMedia: 'manga',
    emoji: '⚡',
    quote: 'Gon, you are light.',
    traits: ['Assassin family', 'Godspeed', 'Best friend'],
    imageUrl: '/images/waifu/killua-zoldyck.jpg',
  },
  {
    name: 'Howl Jenkins',
    series: "Howl's Moving Castle",
    gender: 'boy',
    hairColor: 'blonde',
    eyeColor: 'blue',
    personality: 'genki',
    sourceMedia: 'anime',
    emoji: '🏰',
    quote: "I see no point in living if I can't be beautiful.",
    traits: ['Wizard', 'Vain', 'Heart of gold'],
    imageUrl: '/images/waifu/howl-jenkins.jpg',
  },
  {
    name: 'Edward Elric',
    series: 'Fullmetal Alchemist',
    gender: 'boy',
    hairColor: 'blonde',
    eyeColor: 'amber',
    personality: 'tsundere',
    sourceMedia: 'manga',
    emoji: '🔩',
    quote: "WHO ARE YOU CALLING A BEAN-SIZED ULTRA-SHRIMP?!",
    traits: ['Alchemist', 'Automail', 'Short temper'],
    imageUrl: '/images/waifu/edward-elric.jpg',
  },
  {
    name: 'Sasuke Uchiha',
    series: 'Naruto',
    gender: 'boy',
    hairColor: 'black',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '🌑',
    quote: "I have long since closed my eyes… my only goal is in the darkness.",
    traits: ['Avenger', 'Sharingan', 'Lone wolf'],
    imageUrl: '/images/waifu/sasuke-uchiha.jpg',
  },
  {
    name: 'Nanami Kento',
    series: 'Jujutsu Kaisen',
    gender: 'boy',
    hairColor: 'blonde',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '🕐',
    quote: "I'm a salaryman who just happens to be a sorcerer.",
    traits: ['Office hours', 'Ratio technique', 'Bread lover'],
    imageUrl: '/images/waifu/nanami-kento.jpg',
  },
  {
    name: 'Guts',
    series: 'Berserk',
    gender: 'boy',
    hairColor: 'black',
    eyeColor: 'brown',
    personality: 'kuudere',
    sourceMedia: 'manga',
    emoji: '⚔️',
    quote: "If you're always worried about crushing the ants beneath you, you won't be able to walk.",
    traits: ['Black Swordsman', 'Dragonslayer', 'Unyielding'],
    imageUrl: '/images/waifu/guts.jpg',
  },
]

/** Dropdown option helpers */
export const HAIR_COLOR_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'black', label: '⬛ Black' },
  { value: 'brown', label: '🟫 Brown' },
  { value: 'blonde', label: '🟨 Blonde' },
  { value: 'red', label: '🟥 Red' },
  { value: 'blue', label: '🟦 Blue' },
  { value: 'pink', label: '🩷 Pink' },
  { value: 'white', label: '⬜ White' },
  { value: 'green', label: '🟩 Green' },
  { value: 'purple', label: '🟪 Purple' },
  { value: 'orange', label: '🟧 Orange' },
] as const

export const EYE_COLOR_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'brown', label: '🟤 Brown' },
  { value: 'blue', label: '🔵 Blue' },
  { value: 'green', label: '🟢 Green' },
  { value: 'red', label: '🔴 Red' },
  { value: 'amber', label: '🟠 Amber' },
  { value: 'purple', label: '🟣 Purple' },
  { value: 'pink', label: '🩷 Pink' },
  { value: 'heterochromia', label: '🌈 Heterochromia' },
] as const

export const GENDER_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'girl', label: '♀ Waifu (Girl)' },
  { value: 'boy', label: '♂ Husbando (Boy)' },
] as const

export const PERSONALITY_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'tsundere', label: '😤 Tsundere' },
  { value: 'yandere', label: '🔪 Yandere' },
  { value: 'kuudere', label: '❄️ Kuudere' },
  { value: 'dandere', label: '😶 Dandere' },
  { value: 'genki', label: '🌟 Genki' },
  { value: 'ojou-sama', label: '👑 Ojou-sama' },
  { value: 'tomboy', label: '💪 Tomboy' },
] as const

export const SOURCE_MEDIA_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'anime', label: '📺 Anime' },
  { value: 'manga', label: '📖 Manga' },
  { value: 'game', label: '🎮 Game' },
  { value: 'light-novel', label: '📕 Light Novel' },
] as const
